### ISSUE TITLE
Add ability to directly push to the OpenShift registry (if exposed) as part of the deployment

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/openshift-dd-ext#49]
Currently, users need to manually either push to docker hub or the openshift registry (if available), for the deployment to actually succeed.
We might be able to automate and streamline the whole process, as JBoss Tools does it apparently. @jeffmaury any pointers?

**Comment by jeffmaury** [comment]
The way is was done by JBoss Tools requires to get access the URL of the internal registry of the cluster. This was possible because CDK allowed us to retrieve that information but it seems this is not true anymore with CRC and I found no way to access it from the various config maps. Seems that the way is to retrieve the route in the `openshift-image-registry` namespace but access id denied to a normal user (tested on CRC and Sandbox)

An alternative would be to use ttl.sh as it does not require registration

If you want the details, see https://github.com/jbosstools/jbosstools-openshift/blob/main/plugins/org.jboss.tools.openshift.ui/src/org/jboss/tools/openshift/internal/ui/wizard/deployimage/DeployImageWizard.java and https://github.com/jbosstools/jbosstools-openshift/blob/main/plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/internal/core/docker/PushImageToRegistryJob.java
